### PR TITLE
Changes to make the mockldap tests pass.

### PR DESCRIPTION
**Pull request by aaugustin**
See also https://bitbucket.org/aaugustin/mockldap.

The third commit could probably be improved.

### CODE REVIEW

**Comment by rbarrois** [comment]
Committed on the (other) py3 branch, which was rebased, as ac2b206 and fdf7074.

I didn't pick the "hack" part, not sure of what it does?

**Comment by aaugustin** [comment]
str2dn returned bytes on Python 3. I think it should return str.

An easy way to check this by yourself is to checkout https://bitbucket.org/aaugustin/mockldap, change the python-ldap git URL in tox.ini and run tox. You should see failures without this change.

**Comment by aaugustin** [comment]
I replaced the gross hack by a proper fix in the C code. Does that seem acceptable?

The fix isn't conditional to the Python version -- there's no `LDAPberval_to_str_object` that would return a str both on Python 2 and Python 3.

I don't have an adequate setup for running the test suite. I cannot confirm that it still passes with this change.

**Comment by aaugustin** [comment]
Is there anything I can do to help this move forward? Or is it just a matter of finding the time to review?

Thanks ;-)

**Comment by aaugustin** [comment]
Whee \o/

**Pull request merged**
